# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible_from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible_till_date', models.DateTimeField(default='2999-12-31 23:59')),
            ],
        ),
    ]
