# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/images/banners')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='visible_from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='visible_till_date',
            field=models.DateTimeField(),
        ),
    ]
