# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20160309_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=20)),
                ('data', models.TextField()),
            ],
        ),
    ]
