# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20160310_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopletype',
            name='display_text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='peopletype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
