# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20160310_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletype',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
