# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_peopletype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='img',
            field=models.ImageField(default='/static/images/banners/default.jpg', upload_to='static/images/people'),
            preserve_default=False,
        ),
    ]
