# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_people_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.CharField(max_length=200)),
                ('published_page', models.CharField(max_length=20)),
                ('published_year', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='homepage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='short_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='study_one_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shortnames',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.People'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ShortNames'),
        ),
        migrations.AddField(
            model_name='publication',
            name='conf_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ConferenceType'),
        ),
    ]
