# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20160310_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='personal_page',
            field=models.BooleanField(default=False),
        ),
    ]
