# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_people_personal_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
