# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_auto_20160311_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnames',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lab.People'),
        ),
    ]
