# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20160311_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
