# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_auto_20160311_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors_comma_separated',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(blank=True, to='lab.ShortNames'),
        ),
    ]
