# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_auto_20160317_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
    ]
