# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_remove_publication_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnames',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.People'),
        ),
    ]
