# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_auto_20160317_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNamePublicationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Publication')),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ShortNames')),
            ],
        ),
    ]
