# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_shortnamepublicationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletype',
            name='show_research_interest',
            field=models.BooleanField(default=False),
        ),
    ]
