# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_peopletype_show_research_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('link', models.URLField()),
                ('icon', models.ImageField(upload_to='static/images/social')),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
