# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_auto_20160404_0532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialIcons',
            new_name='SocialIcon',
        ),
    ]
