# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_auto_20160404_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
