# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_auto_20160404_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='interest',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='peopletype',
            name='count_in_one_row',
            field=models.IntegerField(choices=[(4, '4 in a row'), (6, '6 in a row')], default=2),
        ),
        migrations.AlterField(
            model_name='peopletype',
            name='order',
            field=models.IntegerField(default=6),
        ),
    ]
