# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_auto_20160404_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='display_text',
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
