# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_auto_20160404_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='url_path',
            field=models.TextField(default='something'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='display_type',
            field=models.IntegerField(choices=[(1, 'Type = Link'), (2, 'Type = Project'), (3, 'Type = Courses'), (4, 'Type = Under construction')]),
        ),
    ]
