# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_auto_20160404_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='url_path',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
