# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_auto_20160404_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawresourceskeleton',
            name='list_on',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='display_type',
        ),
        migrations.DeleteModel(
            name='RawResourceSkeleton',
        ),
    ]
