# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0035_auto_20160405_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_page',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
